name: myinvo
static_sites:
- name: invo-frontend
  source_dir: pwa
  build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: destos/invo
