name: myinvo
services:
  - name: server
    image:
      registry_type: DOCR
      repository: invo-build
      tag: latest
    run_command: daphne -b 0.0.0.0 -p 8000 invo.asgi:application
    http_port: 8000
    envs:
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
        scope: RUN_TIME
        type: SECRET
      - key: DJANGO_ALLOWED_HOSTS
        value: "${APP_DOMAIN},*.${APP_DOMAIN}"
        scope: RUN_TIME
    routes:
      - path: /api
jobs:
  - name: migrate
    kind: PRE_DEPLOY
    image:
      registry_type: DOCR
      repository: invo-build
      tag: latest
    run_command: ./manage.py migrate
    envs:
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
        scope: RUN_TIME
        type: SECRET
static_sites:
  - name: invo-frontend
    source_dir: pwa
    build_command: npm run build
    environment_slug: node-js
    index_document: index.html
    catchall_document: index.html
    github:
      branch: do
      deploy_on_push: true
      repo: destos/invo
    envs:
      - key: REACT_APP_DOMAIN
        value: "${APP_DOMAIN}"
        scope: BUILD_TIME
  # - name: django-static
  #   image:
  #     registry_type: DOCR
  #     repository: invo-build
  #     tag: latest
  #   # This happens as part of the Python/DJango buildpack:
  #   # build_command: python manage.py collectstatic --noinput
  #   output_dir: staticfiles
  #   routes:
  #     - path: /static
databases:
  # Create a new dev DB:
  - name: db
    engine: PG
    version: "12"
