# Generated by Django 3.1.5 on 2021-01-24 06:03

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210116_2115'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
                ('current_site_objects', accounts.models.CurrentSiteUserManager()),
            ],
        ),
    ]
