# Generated by Django 3.1.2 on 2020-10-23 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0004_auto_20201023_0254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0005_auto_20201023_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'Start'), (1, 'Selecting'), (2, 'Adding'), (5, 'Placing'), (3, 'Increment'), (4, 'Consuming')], default=0)),
                ('exit_condition', django_fsm.FSMIntegerField(choices=[(0, 'Open'), (1, 'Abandoned'), (2, 'Completed')], default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.spacenode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
        ),
    ]
