# Generated by Django 3.1.2 on 2020-10-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_auto_20201023_0254'),
        ('items', '0004_auto_20201023_0254'),
        ('situations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situation',
            options={'get_latest_by': 'modified', 'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='situation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='space',
        ),
        migrations.AddField(
            model_name='situation',
            name='items',
            field=models.ManyToManyField(related_name='situations', to='items.Item'),
        ),
        migrations.AddField(
            model_name='situation',
            name='spaces',
            field=models.ManyToManyField(related_name='situations', to='spaces.SpaceNode'),
        ),
    ]
