# Generated by Django 3.1.5 on 2021-01-24 06:05

from django.db import migrations
import django.db.models.manager
import situations.managers


class Migration(migrations.Migration):

    dependencies = [
        ('situations', '0005_situation_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='situation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site_objects', situations.managers.CurrentSiteSituationManager()),
            ],
        ),
    ]
