# Generated by Django 4.2.11 on 2024-03-25 02:08

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('situations', '0006_auto_20210124_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selecteditem',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterModelOptions(
            name='selectedspace',
            options={'ordering': ('modified',)},
        ),
        migrations.AddField(
            model_name='situation',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='selecteditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='selectedspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Start'), (1, 'Selecting'), (2, 'Adding'), (5, 'Placing'), (6, 'Moving'), (3, 'Increment'), (4, 'Consuming')], default=0),
        ),
    ]
