# Generated by Django 3.1.2 on 2020-10-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20201006_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacenode',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
