# Generated by Django 3.1.2 on 2020-10-05 03:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_auto_20201005_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridspacenode',
            name='grid_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='gridspacenode',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=2),
        ),
    ]
