# Generated by Django 3.1.2 on 2020-10-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_auto_20201006_0439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacenode',
            options={'get_latest_by': ('created',), 'ordering': ('lft', 'parent__name', 'name'), 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
    ]
