# Generated by Django 3.1.3 on 2020-11-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_auto_20201023_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacenode',
            options={'get_latest_by': ('created',), 'ordering': ('lft', 'id'), 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
    ]
