# Generated by Django 3.1.4 on 2020-12-05 04:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django_measurement.models
from measurement.measures import Volume
import measurement.measures.geometry
import spaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_auto_20201129_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacenode',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='spacenode',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_measurement.models.MeasurementField(decimal_places=4, max_digits=8, measure=measurement.measures.geometry.Distance), blank=True, default=spaces.models.default_size, size=3),
        ),
        migrations.AddField(
            model_name='spacenode',
            name='volume',
            field=django_measurement.models.MeasurementField(decimal_places=4, default=Volume("1", "cubic_m"), max_digits=10, measure=measurement.measures.geometry.Volume),
        ),
    ]
