# Generated by Django 3.1.4 on 2020-12-24 21:18

from django.db import migrations
import django_measurement.models
from measurement.measures import Distance
from measurement.measures import Volume
import measurement.measures.geometry


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_auto_20201204_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacenode',
            name='grid_scale',
            field=django_measurement.models.MeasurementField(blank=True, decimal_places=4, default=Distance(metre="0.01"), max_digits=14, measure=measurement.measures.geometry.Distance, null=True),
        ),
        migrations.AlterField(
            model_name='spacenode',
            name='volume',
            field=django_measurement.models.MeasurementField(decimal_places=4, default=Volume(cubic_meter="1"), max_digits=14, measure=measurement.measures.geometry.Volume),
        ),
    ]
