# Generated by Django 3.1.5 on 2021-01-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('spaces', '0009_auto_20201224_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gridspacenode',
            options={},
        ),
        migrations.AddField(
            model_name='spacenode',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
