# Generated by Django 3.1.5 on 2021-01-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('spaces', '0010_auto_20210116_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacenode',
            name='sites',
        ),
        migrations.AddField(
            model_name='spacenode',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
