# Generated by Django 3.1.5 on 2021-01-24 06:05

from django.db import migrations
import django.db.models.manager
import spaces.managers


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0011_auto_20210116_2120'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gridspacenode',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site_objects', spaces.managers.CurrentSiteSpaceNodeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='spacenode',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site_objects', spaces.managers.CurrentSiteSpaceNodeManager()),
            ],
        ),
    ]
