# Generated by Django 3.1.2 on 2020-10-06 04:40

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('spaces', '0004_auto_20201006_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('data', models.JSONField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_items.item_set+', to='contenttypes.contenttype')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='spaces.spacenode')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('count', models.PositiveIntegerField(default=0)),
                ('warning_enabled', models.BooleanField(default=False)),
                ('warning_count', models.PositiveIntegerField(default=10)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='TrackedConsumable',
            fields=[
                ('consumable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.consumable')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('items.consumable',),
        ),
    ]
