# Generated by Django 3.1.2 on 2020-10-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
