# Generated by Django 3.1.2 on 2020-10-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='count',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=13),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='warning_count',
            field=models.DecimalField(decimal_places=4, default='10', max_digits=13),
        ),
    ]
