# Generated by Django 3.1.2 on 2020-10-23 02:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20201007_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='count',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=13),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='warning_count',
            field=models.DecimalField(decimal_places=4, default=Decimal('10'), max_digits=13),
        ),
    ]
