# Generated by Django 3.1.3 on 2020-12-03 04:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20201023_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='warning_count',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=13),
        ),
    ]
