# Generated by Django 3.1.5 on 2021-01-24 06:03

from django.db import migrations
import django.db.models.manager
import items.managers


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210116_2010'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consumable',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site_objects', items.managers.CurrentSiteItemManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site_objects', items.managers.CurrentSiteItemManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tool',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site_objects', items.managers.CurrentSiteItemManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trackedconsumable',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site_objects', items.managers.CurrentSiteItemManager()),
            ],
        ),
    ]
