# Generated by Django 3.1.7 on 2021-03-27 21:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0003_auto_20201023_1636'),
        ('spaces', '0012_auto_20210124_0005'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('items', '0007_auto_20210124_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedConsumableEvent',
            fields=[
                ('consumable_ptr', models.ForeignKey(auto_created=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', related_query_name='+', serialize=False, to='items.consumable')),
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.trackedconsumable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolEvent',
            fields=[
                ('item_ptr', models.ForeignKey(auto_created=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', related_query_name='+', serialize=False, to='items.item')),
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.tool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('data', models.JSONField(blank=True, null=True)),
                ('id', models.IntegerField()),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.item')),
                ('polymorphic_ctype', models.ForeignKey(db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('space', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='spaces.spacenode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableEvent',
            fields=[
                ('item_ptr', models.ForeignKey(auto_created=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', related_query_name='+', serialize=False, to='items.item')),
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('count', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=13)),
                ('warning_enabled', models.BooleanField(default=False)),
                ('warning_count', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=13)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.consumable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
