# Generated by Django 3.1.10 on 2021-05-15 15:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0012_auto_20210124_0005'),
        ('sites', '0002_alter_domain_unique'),
        ('pghistory', '0003_auto_20201023_1636'),
        ('items', '0009_auto_20210327_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('template', models.TextField(verbose_name='Template')),
                ('sites', models.ManyToManyField(to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('name', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='label', verbose_name='Name')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='items.declaration')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='spaces.spacenode'),
        ),
        migrations.CreateModel(
            name='VariantThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.declaration')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.variant')),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='items',
            field=models.ManyToManyField(related_name='variants', through='items.VariantThrough', to='items.Item'),
        ),
        migrations.CreateModel(
            name='DeclarationEvent',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('template', models.TextField(verbose_name='Template')),
                ('id', models.IntegerField()),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='declaration_history', to='items.declaration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='items.declaration'),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='items.declaration'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('name', 'declaration')},
        ),
    ]
