# Generated by Django 4.2.11 on 2024-03-25 02:08

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('spaces', '0012_auto_20210124_0005'),
        ('items', '0010_auto_20210515_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='declarationevent',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consumableevent',
            name='item_ptr',
            field=models.ForeignKey(auto_created=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, serialize=False, to='items.item'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='itemevent',
            name='declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='items.declaration'),
        ),
        migrations.AlterField(
            model_name='itemevent',
            name='polymorphic_ctype',
            field=models.ForeignKey(db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='itemevent',
            name='space',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='spaces.spacenode'),
        ),
        migrations.AlterField(
            model_name='toolevent',
            name='item_ptr',
            field=models.ForeignKey(auto_created=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, serialize=False, to='items.item'),
        ),
        migrations.AlterField(
            model_name='trackedconsumableevent',
            name='consumable_ptr',
            field=models.ForeignKey(auto_created=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, serialize=False, to='items.consumable'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variantthrough',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='consumable',
            trigger=pgtrigger.compiler.Trigger(name='consumable_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            INSERT INTO "items_consumableevent"\n                ("item_ptr_id", "count", "warning_enabled", "warning_count", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."item_ptr_id", NEW."count", NEW."warning_enabled", NEW."warning_count", NOW(), \'consumable_snapshot\', NEW."item_ptr_id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='0c525991288c8e53ef10085233ea4b10a88d73c0', operation='INSERT', pgid='pgtrigger_consumable_snapshot_insert_dd029', table='items_consumable', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='consumable',
            trigger=pgtrigger.compiler.Trigger(name='consumable_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."item_ptr_id" IS DISTINCT FROM (NEW."item_ptr_id") OR OLD."count" IS DISTINCT FROM (NEW."count") OR OLD."warning_enabled" IS DISTINCT FROM (NEW."warning_enabled") OR OLD."warning_count" IS DISTINCT FROM (NEW."warning_count"))', func='\n            INSERT INTO "items_consumableevent"\n                ("item_ptr_id", "count", "warning_enabled", "warning_count", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."item_ptr_id", NEW."count", NEW."warning_enabled", NEW."warning_count", NOW(), \'consumable_snapshot\', NEW."item_ptr_id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='550ae6b27d5e517ad3878e8815670f9c9c4725ac', operation='UPDATE', pgid='pgtrigger_consumable_snapshot_update_9c580', table='items_consumable', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='declaration',
            trigger=pgtrigger.compiler.Trigger(name='declaration_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            INSERT INTO "items_declarationevent"\n                ("deleted", "deleted_by_cascade", "created", "modified", "name", "template", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."deleted", NEW."deleted_by_cascade", NEW."created", NEW."modified", NEW."name", NEW."template", NEW."id", NOW(), \'declaration_snapshot\', NEW."id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='401c69608eec482ece34999b7323f26b0158d7c3', operation='INSERT', pgid='pgtrigger_declaration_snapshot_insert_f4402', table='items_declaration', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='declaration',
            trigger=pgtrigger.compiler.Trigger(name='declaration_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."deleted" IS DISTINCT FROM (NEW."deleted") OR OLD."deleted_by_cascade" IS DISTINCT FROM (NEW."deleted_by_cascade") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."template" IS DISTINCT FROM (NEW."template") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='\n            INSERT INTO "items_declarationevent"\n                ("deleted", "deleted_by_cascade", "created", "modified", "name", "template", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."deleted", NEW."deleted_by_cascade", NEW."created", NEW."modified", NEW."name", NEW."template", NEW."id", NOW(), \'declaration_snapshot\', NEW."id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='8e6c5ffb8319e854dc7ac4ffce298b63bbb2f6bf', operation='UPDATE', pgid='pgtrigger_declaration_snapshot_update_2b3b7', table='items_declaration', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='declaration',
            trigger=pgtrigger.compiler.Trigger(name='protect_deletes', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;", hash='d612d2be29187312b1ce865f350704fb0e0777ec', operation='DELETE', pgid='pgtrigger_protect_deletes_4d329', table='items_declaration', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='item_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            INSERT INTO "items_itemevent"\n                ("polymorphic_ctype_id", "deleted", "deleted_by_cascade", "created", "modified", "name", "data", "space_id", "declaration_id", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."polymorphic_ctype_id", NEW."deleted", NEW."deleted_by_cascade", NEW."created", NEW."modified", NEW."name", NEW."data", NEW."space_id", NEW."declaration_id", NEW."id", NOW(), \'item_snapshot\', NEW."id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='26dd8821100623d00e5e24a6a92ebf73a1747d7d', operation='INSERT', pgid='pgtrigger_item_snapshot_insert_a62ad', table='items_item', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='item_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."polymorphic_ctype_id" IS DISTINCT FROM (NEW."polymorphic_ctype_id") OR OLD."deleted" IS DISTINCT FROM (NEW."deleted") OR OLD."deleted_by_cascade" IS DISTINCT FROM (NEW."deleted_by_cascade") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."data" IS DISTINCT FROM (NEW."data") OR OLD."space_id" IS DISTINCT FROM (NEW."space_id") OR OLD."declaration_id" IS DISTINCT FROM (NEW."declaration_id") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='\n            INSERT INTO "items_itemevent"\n                ("polymorphic_ctype_id", "deleted", "deleted_by_cascade", "created", "modified", "name", "data", "space_id", "declaration_id", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."polymorphic_ctype_id", NEW."deleted", NEW."deleted_by_cascade", NEW."created", NEW."modified", NEW."name", NEW."data", NEW."space_id", NEW."declaration_id", NEW."id", NOW(), \'item_snapshot\', NEW."id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='7f3594e2aa3b02170829462f080281b6d11784f0', operation='UPDATE', pgid='pgtrigger_item_snapshot_update_5343e', table='items_item', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tool',
            trigger=pgtrigger.compiler.Trigger(name='tool_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            INSERT INTO "items_toolevent"\n                ("item_ptr_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."item_ptr_id", NOW(), \'tool_snapshot\', NEW."item_ptr_id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='8d559700bdd15f2a6c9e710b8e620cf5580bdafa', operation='INSERT', pgid='pgtrigger_tool_snapshot_insert_093ed', table='items_tool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tool',
            trigger=pgtrigger.compiler.Trigger(name='tool_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."item_ptr_id" IS DISTINCT FROM (NEW."item_ptr_id"))', func='\n            INSERT INTO "items_toolevent"\n                ("item_ptr_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."item_ptr_id", NOW(), \'tool_snapshot\', NEW."item_ptr_id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='3906170c9b8097dd57ec839e7ae0faf483ee6d95', operation='UPDATE', pgid='pgtrigger_tool_snapshot_update_2b39d', table='items_tool', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trackedconsumable',
            trigger=pgtrigger.compiler.Trigger(name='trackedconsumable_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            INSERT INTO "items_trackedconsumableevent"\n                ("consumable_ptr_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."consumable_ptr_id", NOW(), \'trackedconsumable_snapshot\', NEW."consumable_ptr_id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='d44de71c3c55533ff2564c4f8c7ba691844f3064', operation='INSERT', pgid='pgtrigger_trackedconsumable_snapshot_insert_14ae4', table='items_trackedconsumable', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trackedconsumable',
            trigger=pgtrigger.compiler.Trigger(name='trackedconsumable_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."consumable_ptr_id" IS DISTINCT FROM (NEW."consumable_ptr_id"))', func='\n            INSERT INTO "items_trackedconsumableevent"\n                ("consumable_ptr_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."consumable_ptr_id", NOW(), \'trackedconsumable_snapshot\', NEW."consumable_ptr_id", _pgh_attach_context());\n            RETURN NULL;\n        ', hash='336fd620a7e4a97cc8d647fe44a28d12b1d46263', operation='UPDATE', pgid='pgtrigger_trackedconsumable_snapshot_update_9838a', table='items_trackedconsumable', when='AFTER')),
        ),
    ]
